Work Project 3.6/config/routes.rb
Rails.application.routes.draw do
  get 'admin_control/admin_panel'
  get 'admin_control/admin_panel_create'
  get 'admin_control/admin_panel_delete'
  get 'admin_control/admin_panel_update'
  get 'admin_control/create_user'
  get 'admin_control/delete_user'
  get 'admin_control/edit_user'
  root 'candidate_details#index'
  resources :candidate_details
  devise_for :users
  get "Admin_Panel", to: "admin_control#admin_panel", as:"panel"
  get "Admin_Panel_Create", to:"admin_control#admin_panel_create", as:"panel_create"
  post "Admin_Panel", to: "admin_page#admin_panel"
  get "Admin_Panel_Edit", to: "admin_control#admin_panel_update",as: "panel_edit"
  get "Admin_Panel_Delete", to: "admin_control#admin_panel_delete",as: "panel_delete"
  post "Create_User",to: "admin_control#create_user",as:"create_user"
  post "Edit_User", to:"admin_control#edit_user",as:"edit_user"
  post "Delete_User", to:"admin_control#delete_user",as:"delete_user"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Work Project 3.6/app/models/candidate_detail.rb
class CandidateDetail < ApplicationRecord
  validates :s_no, presence: {message:"S.No. must specified"},uniqueness: {message:"S.No. already exist."}
  validates :src_reg, presence:true, format:{with: /\AR/,message: "Please enter Source of Regeistration in following format -> N/state abbrivation."}
  validates :src_reg, length:{is: 4,message:"Please enter state abbrivation correctely (only 2 letters of state abbrivation."}
  validates :reg_no,presence: true
  validate :match_regno
  validates :name, presence:{message:"Name must specified."}
  validates :gender, presence:{message:"Gender must specified."}
  validates :age, presence: {message:"Age must specified."}
  validates :email, presence:{message:"Email is required."}, uniqueness: {message:"Email is already exist."},format:{with:/@/,message:"Email must contain @."}
  validates :contact_no, presence:{message:"Contact Number is required."},uniqueness: {message:"Contact Number is already exist."},length: {is: 10,message:"Contact Numbers must be 10 digits."}
  validate :check_remark
  validate :status_now
  def match_regno
    unless reg_no=="NZ/"+src_reg+"/"+s_no.to_s
      errors.add(:reg_no,"Registration Number is incorrect. It must be in following pattern NZ/Source of Registration/S.No.")
    end
  end
  def check_remark
    unless (1..10)===remarks_mobility
      errors.add(:remarks_mobility,"Remark_mobility must be between the range 1 to 10.")
    end
  end
  def status_now
    unless ["pending", "joined", "joining", "not interested", "study", "not responding"].include?status
      errors.add(:status,"Status must be one of following -> pending, joined, joining, not interested, study, not responding.")
    end
  end

end

Work Project 3.6/app/controllers/candidate_details_controller.rb
class CandidateDetailsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_candidate_detail, only: [:show, :edit, :update, :destroy]

  def index
    @candidate_details = CandidateDetail.all
  end
  def show
  end
  def new
    @candidate_detail = CandidateDetail.new
  end
  def edit
  end
  def create
    @candidate_detail = CandidateDetail.new(candidate_detail_params)
    respond_to do |format|
      if @candidate_detail.save
        format.html { redirect_to @candidate_detail, notice: 'Candidate detail was successfully created.' }
        format.json { render :show, status: :created, location: @candidate_detail }
      else
        format.html { render :new }
        format.json { render json: @candidate_detail.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    respond_to do |format|
      if @candidate_detail.update(candidate_detail_params)
        format.html { redirect_to @candidate_detail, notice: 'Candidate details was successfully updated.' }
        format.json { render :show, status: :ok, location: @candidate_detail }
      else
        format.html { render :edit }
        format.json { render json: @candidate_detail.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @candidate_detail.destroy
    respond_to do |format|
      format.html { redirect_to candidate_details_url, notice: 'Candidate details was successfully deleted.' }
      format.json { head :no_content }
    end
  end
  private
    def set_candidate_detail
      @candidate_detail = CandidateDetail.find(params[:id])
    end
    def candidate_detail_params
      params.require(:candidate_detail).permit(:s_no, :src_reg, :zone, :DOR, :reg_no, :name, :gender, :age, :address, :branch, :email, :contact_no, :state, :qualification, :specialization, :experience, :remarks_mobility, :DOC, :status)
    end
end

Work Project 3.6/app/views/admin_control/admin_panel.html.erb
<p id="notice"><%= notice %></p>
<h1>Admin Pages</h1>
<div class="table-responsive table-bordered">
  <table class="table">
    <thead>
    <tr>
      <th>Email</th>
    </tr>
    </thead>
    <tbody>
    <% @all_email.each do |mail| %>
      <tr>
        <td><%= mail.email %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<div class="text-center">
  <br>
<%= link_to 'Create User', panel_create_path, class:"btn btn-default" %>
<%= link_to 'Edit User', panel_edit_path,class:"btn btn-info" %>
<%= link_to 'Delete User',panel_delete_path,class:"btn btn-warning" %><br><br>
<%= link_to 'Back',candidate_details_path,class: "btn btn-default" %>
</div>

Work Project 3.6/app/views/admin_control/admin_panel_create.html.erb
<div class="main-agileinfo">
  <div class="agileits-top">
    <h1>Create User</h1>
    <%= form_tag create_user_path do |user| %>
      <div class="field">
        <%= label_tag :email ,"Email"%>
        <%= email_field_tag :email %>
      </div>
      <div class="field">
        <%= label_tag :password,"Password (6 characters minimum)" %>
        <%= password_field_tag :password%>
      </div>
      <div class="field">
        <%=label_tag :password_confirmation,"Password Confirmation" %>
        <%=password_field_tag :Password_confirmation %>
      </div>
      <div class="actions">
        <%= submit_tag "Create User" %>
      </div>
    <% end %>
  </div>
</div>

Work Project 3.6/app/views/admin_control/admin_panel_delete.html.erb
<div class="main-agileinfo">
  <div class="agileits-top">
    <h1>Delete User</h1>
    <%= form_tag delete_user_path do |user| %>
      <div class="field">
        <%= label_tag :email ,"Email"%>
        <%= email_field_tag :email %>
      </div>
      <div class="actions">
        <%= submit_tag "Delete User" %>
      </div>
    <% end %>
  </div>
</div>

Work Project 3.6/app/views/admin_control/admin_panel_update.html.erb
<div class="main-agileinfo">
  <div class="agileits-top">
    <h1>Update User</h1>
    <%= form_tag edit_user_path do |user| %>
      <div class="field">
        <%=label_tag :prev_email,"Previous Email" %>
        <%=email_field_tag :prev_email %>
      </div>
      <div class="field">
        <%= label_tag :email ,"New Email"%>
        <%= email_field_tag :email %>
      </div>
      <div class="field">
        <%= label_tag :password,"Password (6 characters minimum)" %>
        <%= password_field_tag :password%>
      </div>
      <div class="field">
        <%=label_tag :password_confirmation,"Password Confirmation" %>
        <%=password_field_tag :Password_confirmation %>
      </div>
      <div class="actions">
        <%= submit_tag "Edit User" %>
      </div>
    <% end %>
  </div>
</div>