Work Project 3/config/routes.rb
Rails.application.routes.draw do
  root 'sessions#login_page'
  resources :candidate_details
  resources :sessions
  post 'sessions/login_page'
  get 'sessions/signup_page'
  get 'sessions/logout'
  get 'sessions/admin_page'
  get 'signup', to: 'login_data#new', as: 'signup'
  post '/cd', to:'candidate_details#index', as: 'home'
  get 'logout', to: 'sessions#logout', as: 'logout'

  resources :login_data
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Work Project 3/app/models/login_datum.rb
class LoginDatum < ApplicationRecord
  has_secure_password
end

Work Project 3/app/controllers/candidate_details_controller.rb
class CandidateDetailsController < ApplicationController
  before_action :set_candidate_detail, only: [:show, :edit, :update, :destroy]

  # GET /candidate_details
  # GET /candidate_details.json
  def index
    @candidate_details = CandidateDetail.all
  end

  # GET /candidate_details/1
  # GET /candidate_details/1.json
  def show
  end

  # GET /candidate_details/new
  def new
    @candidate_detail = CandidateDetail.new
  end

  # GET /candidate_details/1/edit
  def edit
  end

  # POST /candidate_details
  # POST /candidate_details.json
  def create
    @candidate_detail = CandidateDetail.new(candidate_detail_params)

    respond_to do |format|
      if @candidate_detail.save
        format.html { redirect_to @candidate_detail, notice: 'Candidate detail was successfully created.' }
        format.json { render :show, status: :created, location: @candidate_detail }
      else
        format.html { render :new }
        format.json { render json: @candidate_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidate_details/1
  # PATCH/PUT /candidate_details/1.json
  def update
    respond_to do |format|
      if @candidate_detail.update(candidate_detail_params)
        format.html { redirect_to @candidate_detail, notice: 'Candidate detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @candidate_detail }
      else
        format.html { render :edit }
        format.json { render json: @candidate_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidate_details/1
  # DELETE /candidate_details/1.json
  def destroy
    @candidate_detail.destroy
    respond_to do |format|
      format.html { redirect_to candidate_details_url, notice: 'Candidate detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidate_detail
      @candidate_detail = CandidateDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidate_detail_params
      params.require(:candidate_detail).permit(:s_no, :src_reg, :zone, :DOR, :reg_no, :name, :gender, :age, :address, :branch, :email, :contact_no, :state, :qualification, :specialization, :experience, :remark_mobility, :DOC, :status)
    end
end

Work Project 3/app/controllers/login_data_controller.rb
class LoginDataController < ApplicationController
  before_action :set_login_datum, only: [:show, :edit, :update, :destroy]

  # GET /login_data
  # GET /login_data.json
  def index
    @login_data = LoginDatum.all
  end

  # GET /login_data/1
  # GET /login_data/1.json
  def show
  end

  # GET /login_data/new
  def new
    @login_datum = LoginDatum.new
  end

  # GET /login_data/1/edit
  def edit
  end

  # POST /login_data
  # POST /login_data.json
  def create
    @login_datum = LoginDatum.new(login_datum_params)

    respond_to do |format|
      if @login_datum.save
        format.html { redirect_to root_path, notice: 'Login datum was successfully created.' }
        format.json { render :show, status: :created, location: @login_datum }
      else
        format.html { render :new }
        format.json { render json: @login_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /login_data/1
  # PATCH/PUT /login_data/1.json
  def update
    respond_to do |format|
      if @login_datum.update(login_datum_params)
        format.html { redirect_to @login_datum, notice: 'Login datum was successfully updated.' }
        format.json { render :show, status: :ok, location: @login_datum }
      else
        format.html { render :edit }
        format.json { render json: @login_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /login_data/1
  # DELETE /login_data/1.json
  def destroy
    @login_datum.destroy
    respond_to do |format|
      format.html { redirect_to login_data_url, notice: 'Login datum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_login_datum
      @login_datum = LoginDatum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def login_datum_params
      params.require(:login_datum).permit(:username, :password, :password_confirmation)
    end
end

Work Project 3/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login_page
    user=LoginDatum.find_by_username(params[:username])
    if user&&user.authenticate(params[:password])
      redirect_to candidate_detail_path
    else
      flash.now[:alert]='Incorrect Username or Password'
      render "login_page"
    end
  end

  def signup_page
  end

  def logout
    redirect_to root_path, notice: 'Logged out successfully'
  end

  def admin_page
  end
end

Work Project 3/app/helpers/login_data_helper.rb
module LoginDataHelper
end

Work Project 3/app/helpers/sessions_helper.rb
module SessionsHelper
end

Work Project 3/app/views/candidate_details/_form.html.erb
<%= form_with(model: candidate_detail, local: true) do |form| %>
  <% if candidate_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(candidate_detail.errors.count, "error") %> prohibited this candidate_detail from being saved:</h2>

      <ul>
      <% candidate_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :s_no %>
    <%= form.number_field :s_no %>
  </div>

  <div class="field">
    <%= form.label :src_reg %>
    <%= form.text_field :src_reg %>
  </div>

  <div class="field">
    <%= form.label :zone %>
    <%= form.text_field :zone %>
  </div>

  <div class="field">
    <%= form.label :DOR %>
    <%= form.date_select :DOR %>
  </div>

  <div class="field">
    <%= form.label :reg_no %>
    <%= form.text_field :reg_no %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :branch %>
    <%= form.text_field :branch %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :contact_no %>
    <%= form.number_field :contact_no %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :qualification %>
    <%= form.text_field :qualification %>
  </div>

  <div class="field">
    <%= form.label :specialization %>
    <%= form.text_field :specialization %>
  </div>

  <div class="field">
    <%= form.label :experience %>
    <%= form.text_area :experience %>
  </div>

  <div class="field">
    <%= form.label :remark_mobility %>
    <%= form.number_field :remark_mobility %>
  </div>

  <div class="field">
    <%= form.label :DOC %>
    <%= form.date_select :DOC %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Work Project 3/app/views/candidate_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Candidate Details</h1>

<table>
  <thead>
  <tr>
    <th>S.No.</th>
    <th>Registration No.</th>
    <th>Name</th>
    <th>Branch</th>
    <th>Email</th>
    <th>Contact No.</th>
    <th>Status</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @candidate_details.each do |candidate_detail| %>
    <tr>
      <td><%= candidate_detail.s_no %></td>
      <td><%= candidate_detail.reg_no %></td>
      <td><%= candidate_detail.name %></td>
      <td><%= candidate_detail.branch %></td>
      <td><%= candidate_detail.email %></td>
      <td><%= candidate_detail.contact_no %></td>
      <td><%= candidate_detail.status %></td>
      <td><%= link_to 'Read', candidate_detail %></td>
      <td><%= link_to 'Update', edit_candidate_detail_path(candidate_detail) %></td>
      <td><%= link_to 'Delete', candidate_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create', new_candidate_detail_path %>
<%=link_to 'Filter' %><br>
<%=link_to 'Logout', logout_path %>

Work Project 3/app/views/candidate_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>S no:</strong>
  <%= @candidate_detail.s_no %>
</p>

<p>
  <strong>Src reg:</strong>
  <%= @candidate_detail.src_reg %>
</p>

<p>
  <strong>Zone:</strong>
  <%= @candidate_detail.zone %>
</p>

<p>
  <strong>Dor:</strong>
  <%= @candidate_detail.DOR %>
</p>

<p>
  <strong>Reg no:</strong>
  <%= @candidate_detail.reg_no %>
</p>

<p>
  <strong>Name:</strong>
  <%= @candidate_detail.name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @candidate_detail.gender %>
</p>

<p>
  <strong>Age:</strong>
  <%= @candidate_detail.age %>
</p>

<p>
  <strong>Address:</strong>
  <%= @candidate_detail.address %>
</p>

<p>
  <strong>Branch:</strong>
  <%= @candidate_detail.branch %>
</p>

<p>
  <strong>Email:</strong>
  <%= @candidate_detail.email %>
</p>

<p>
  <strong>Contact no:</strong>
  <%= @candidate_detail.contact_no %>
</p>

<p>
  <strong>State:</strong>
  <%= @candidate_detail.state %>
</p>

<p>
  <strong>Qualification:</strong>
  <%= @candidate_detail.qualification %>
</p>

<p>
  <strong>Specialization:</strong>
  <%= @candidate_detail.specialization %>
</p>

<p>
  <strong>Experience:</strong>
  <%= @candidate_detail.experience %>
</p>

<p>
  <strong>Remark mobility:</strong>
  <%= @candidate_detail.remark_mobility %>
</p>

<p>
  <strong>Doc:</strong>
  <%= @candidate_detail.DOC %>
</p>

<p>
  <strong>Status:</strong>
  <%= @candidate_detail.status %>
</p>

<%= link_to 'Edit', edit_candidate_detail_path(@candidate_detail) %> |
<%= link_to 'Back', candidate_details_path %>

Work Project 3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkProject3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Work Project 3/app/views/login_data/_form.html.erb
<%= form_with(model: login_datum, local: true) do |form| %>
  <% if login_datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(login_datum.errors.count, "error") %> prohibited this login_datum from being saved:</h2>

      <ul>
      <% login_datum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit "Sign Up"%>
  </div>
<% end %>

Work Project 3/app/views/login_data/edit.html.erb
<h1>Editing Login Datum</h1>

<%= render 'form', login_datum: @login_datum %>

<%= link_to 'Show', @login_datum %> |
<%= link_to 'Back', login_data_path %>

Work Project 3/app/views/login_data/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Login Data</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @login_data.each do |login_datum| %>
      <tr>
        <td><%= login_datum.username %></td>
        <td><%= link_to 'Show', login_datum %></td>
        <td><%= link_to 'Edit', edit_login_datum_path(login_datum) %></td>
        <td><%= link_to 'Destroy', login_datum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Login Datum', new_login_datum_path %>

Work Project 3/app/views/login_data/new.html.erb
<h1>New Login Datum</h1>

<%= render 'form', login_datum: @login_datum %>

<%= link_to 'Back', root_path %>

Work Project 3/app/views/login_data/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @login_datum.username %>
</p>

<%= link_to 'Edit', edit_login_datum_path(@login_datum) %> |
<%= link_to 'Back', login_data_path %>