Work Project 4/config/routes.rb
Rails.application.routes.draw do
  get 'Filter', to: "filter_page#filter_menu", as:"filter"
  post "Filter_Result",to: "filter_page#filter_result", as: "filter_result"

  root 'candidate_details#index'
  resources :candidate_details
  devise_for :users
  get "Admin_Panel", to: "admin_control#admin_panel", as:"panel"
  get "Admin_Panel_Create", to:"admin_control#admin_panel_create", as:"panel_create"
  post "Admin_Panel", to: "admin_page#admin_panel"
  get "Admin_Panel_Edit", to: "admin_control#admin_panel_update",as: "panel_edit"
  get "Admin_Panel_Delete", to: "admin_control#admin_panel_delete",as: "panel_delete"
  post "Create_User",to: "admin_control#create_user",as:"create_user"
  post "Edit_User", to:"admin_control#edit_user",as:"edit_user"
  post "Delete_User", to:"admin_control#delete_user",as:"delete_user"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Work Project 4/app/models/candidate_detail.rb
class CandidateDetail < ApplicationRecord

  validates :name, presence:{message:"must specified."}
  validates :gender, presence:{message:"must specified."}
  validates :gender, presence:true, inclusion: { in: ["Male", "Female"], message: 'Only male and female allowed' }
  validates :age, presence: {message:"must specified."}
  validates :email, presence:{message:"is required."}, uniqueness: {message:"is already exist."},format:{with:/@/,message:"Email must contain @."}
  validates :contact_no, presence:{message:"is required."},uniqueness: {message:"is already exist."},length: {is: 10,message:"must be 10 digits."}
  
  def self.filter_result(sql_statement,parameter)
    user=CandidateDetail.find_by_sql([sql_statement,parameter])
    return user
  end
  def self.filter_count(sql_statement,parameter)
    user=CandidateDetail.find_by_sql([sql_statement,parameter])
    return user.count
  end
  def self.update_reg(state,id)
    print state.to_s
    user=CandidateDetail.find_by_id(id)
    user.src_reg="R/"+state.to_s
    user.reg_no="NZ/R/"+state.to_s+"/"+id.to_s
    user.save

  end

end

Work Project 4/app/controllers/candidate_details_controller.rb
class CandidateDetailsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_candidate_detail, only: [:show, :edit, :update, :destroy]
  
  def index
    @candidate_details = CandidateDetail.all
  end
  def show
  end
  def new
    @candidate_detail = CandidateDetail.new
  end
  def edit
  end
  def create
    @state_hash={
    "AP":"Andhra Pradesh",
    "AR":"Arunachal Pradesh",
    "AS":"Assam",
    "BR":"Bihar",
    "CG":"Chhattisgarh",
    "Chandigarh":"Chandigarh",
    "DN":"Dadra and Nagar Haveli",
    "DD":"Daman and Diu",
    "DL":"Delhi",
    "GA":"Goa",
    "GJ":"Gujarat",
    "HR":"Haryana",
    "HP":"Himachal Pradesh",
    "JK":"Jammu and Kashmir",
    "JH":"Jharkhand",
    "KA":"Karnataka",
    "KL":"Kerala",
    "MP":"Madhya Pradesh",
    "MH":"Maharashtra",
    "MN":"Manipur",
    "ML":"Meghalaya",
    "MZ":"Mizoram",
    "NL":"Nagaland",
    "OR":"Orissa",
    "PB":"Punjab",
    "PY":"Pondicherry",
    "RJ":"Rajasthan",
    "SK":"Sikkim",
    "TN":"Tamil Nadu",
    "TR":"Tripura",
    "UP":"Uttar Pradesh",
    "UK":"Uttarakhand",
    "WB":"West Bengal"
  }
    @candidate_detail = CandidateDetail.new(candidate_detail_params)
    @candidate_detail.src_reg='R/'+@state_hash.key(@candidate_detail.state).to_s
    respond_to do |format|
      if @candidate_detail.save
        @candidate_detail.update(s_no: @candidate_detail.id)
        @candidate_detail.update(reg_no: 'NZ/'+@candidate_detail.src_reg+"/"+@candidate_detail.id.to_s)
        format.html { redirect_to @candidate_detail, notice: 'Candidate detail was successfully created.' }
        format.json { render :show, status: :created, location: @candidate_detail }
      else
        format.html { render :new }
        format.json { render json: @candidate_detail.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    @state_hash={
        "AP":"Andhra Pradesh",
        "AR":"Arunachal Pradesh",
        "AS":"Assam",
        "BR":"Bihar",
        "CG":"Chhattisgarh",
        "Chandigarh":"Chandigarh",
        "DN":"Dadra and Nagar Haveli",
        "DD":"Daman and Diu",
        "DL":"Delhi",
        "GA":"Goa",
        "GJ":"Gujarat",
        "HR":"Haryana",
        "HP":"Himachal Pradesh",
        "JK":"Jammu and Kashmir",
        "JH":"Jharkhand",
        "KA":"Karnataka",
        "KL":"Kerala",
        "MP":"Madhya Pradesh",
        "MH":"Maharashtra",
        "MN":"Manipur",
        "ML":"Meghalaya",
        "MZ":"Mizoram",
        "NL":"Nagaland",
        "OR":"Orissa",
        "PB":"Punjab",
        "PY":"Pondicherry",
        "RJ":"Rajasthan",
        "SK":"Sikkim",
        "TN":"Tamil Nadu",
        "TR":"Tripura",
        "UP":"Uttar Pradesh",
        "UK":"Uttarakhand",
        "WB":"West Bengal"
    }
    respond_to do |format|
      if @candidate_detail.update(candidate_detail_params)
        CandidateDetail.update_reg(@state_hash.key(@candidate_detail.state),@candidate_detail.id)
        format.html { redirect_to @candidate_detail, notice: 'Candidate details was successfully updated.' }
        format.json { render :show, status: :ok, location: @candidate_detail }
      else
        format.html { render :edit }
        format.json { render json: @candidate_detail.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @candidate_detail.destroy
    respond_to do |format|
      format.html { redirect_to candidate_details_url, notice: 'Candidate details was successfully deleted.' }
      format.json { head :no_content }
    end
  end
  private
    def set_candidate_detail
      @candidate_detail = CandidateDetail.find(params[:id])
    end
    def candidate_detail_params
      params.require(:candidate_detail).permit(:s_no, :src_reg, :zone, :DOR, :reg_no, :name, :gender, :age, :address, :branch, :email, :contact_no, :state, :qualification, :specialization, :experience, :remarks_mobility, :DOC, :status)
    end
end

Work Project 4/app/helpers/candidate_details_helper.rb
module CandidateDetailsHelper
end

Work Project 4/app/views/candidate_details/_form.html.erb
<div class="main-agileinfo">
<div class="agileits-top">
<%= form_with(model: candidate_detail, local: true) do |form| %>
  <% if candidate_detail.errors.any? %>
    <div class="alert alert-warning" >
      <h2><%= pluralize(candidate_detail.errors.count, "error") %> prohibited this candidate_detail from being saved:</h2>
      <ul>
      <% candidate_detail.errors.full_messages.each do |message| %>
        <li class="alert alert-danger"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :DOR ,"Date of registration"%><br>
    <%= form.date_select :DOR %>
  </div>
  <div class="field">
    <%= form.label :name ,"Name"%>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :gender,"Gender" %>
    <%= form.select :gender ,["Male","Female"]%>
  </div>
  <div class="field">
    <%= form.label :age ,"Age"%><br>
    <%= form.number_field :age %>
  </div>
  <div class="field">
    <%= form.label :branch,"Branch" %>
    <%= form.text_field :branch %>
  </div>
  <div class="field">
    <%= form.label :email,"Email" %>
    <%= form.text_field :email %>
  </div>
  <div class="field">
    <%= form.label :contact_no,"Contact number" %><br>
    <%= form.number_field :contact_no %>
  </div>
  <div class="field">
    <%= form.label :address ,"Address"%><br>
    <%= form.text_area :address %>
  </div>
  <div class="field">
    <%= form.label :state,"State " %><br>
    <%= form.select :state, ["Andhra Pradesh",
   "Arunachal Pradesh",
   "Assam",
   "Bihar",
   "Chhattisgarh",
   "Chandigarh",
   "Dadra and Nagar Haveli",
   "Daman and Diu",
   "Delhi",
   "Goa",
   "Gujarat",
   "Haryana",
   "Himachal Pradesh",
   "Jammu and Kashmir",
   "Jharkhand",
   "Karnataka",
   "Kerala",
   "Madhya Pradesh",
   "Maharashtra",
   "Manipur",
   "Meghalaya",
   "Mizoram",
   "Nagaland",
   "Orissa",
   "Punjab",
   "Pondicherry",
   "Rajasthan",
   "Sikkim",
   "Tamil Nadu",
   "Tripura",
   "Uttar Pradesh",
   "Uttarakhand",
   "West Bengal"]%>
  </div>
  <div class="field">
    <%= form.label :zone ,"Zone"%>
    <%= form.text_field :zone %>
  </div>
  <div class="field">
    <%= form.label :qualification,"Qualification" %>
    <%= form.text_field :qualification %>
  </div>
  <div class="field">
    <%= form.label :specialization ,"Specialization"%>
    <%= form.text_field :specialization %>
  </div>
  <div class="field">
    <%= form.label :experience,"Experience" %>
    <%= form.text_field :experience %>
  </div>
  <div class="field">
    <%= form.label :remarks_mobility ,"Remarks Mobility"%><br>
    <%= form.select :remarks_mobility,[1,2,3,4,5,6,7,8,9,10] %>
  </div>
  <div class="field">
    <%= form.label :DOC ,"Date of closure"%><br>
    <%= form.date_select :DOC,:include_blank=>true%>
  </div>
  <div class="field">
    <%= form.label :status,"Status" %><br>
    <%= form.select :status,["Pending","Joined","Joining","Studying","Not interested","Not responding"] %>
  </div>
  <div class="actions">
    <%= form.submit%>
  </div>
<% end %>
</div>
</div>

Work Project 4/app/views/candidate_details/edit.html.erb
<br><br><br>
<h1>Editing Candidate Detail</h1>
<%= render 'form', candidate_detail: @candidate_detail %>
<div class="text-center">
<%= link_to 'Show', @candidate_detail,class:"btn btn-default" %> |
<%= link_to 'Back', candidate_details_path ,class:"btn btn-default"%>
</div>

Work Project 4/app/views/candidate_details/index.html.erb
<h1>Candidate Details</h1>
<div class="table-responsive table-bordered">
<table class="table">
  <thead>
    <tr>
      <th>S.No.</th>
      <th>Registration Number</th>
      <th>Name</th>
      <th>Branch</th>
      <th>Email</th>
      <th>Contact Number</th>
      <th>Status</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @candidate_details.each do |candidate_detail| %>
      <tr>
        <td><%= candidate_detail.id %></td>
        <td><%= candidate_detail.reg_no %></td>
        <td><%= candidate_detail.name %></td>
        <td><%= candidate_detail.branch %></td>
        <td><%= candidate_detail.email %></td>
        <td><%= candidate_detail.contact_no %></td>
        <td><%= candidate_detail.status %></td>
        <td><%= link_to 'Read', candidate_detail,class:"btn btn-default" %>
        | <%= link_to 'Update', edit_candidate_detail_path(candidate_detail),class:"btn btn-info" %>
        | <%= link_to 'Delete', candidate_detail, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-warning" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>
<div class="text-center">
<%= link_to 'Create', new_candidate_detail_path,class:"btn btn-default"%> |
<%= link_to 'Filter',filter_path,class:"btn btn-default"%>
  <%if current_user && current_user.admin %>
    | <%=link_to "Admin Panel", panel_path,class: "btn btn-default" %>
  <%end %>
</div>

Work Project 4/app/views/candidate_details/new.html.erb
<br><br><br>
<h1>New Candidate Detail</h1>
<%= render 'form', candidate_detail: @candidate_detail %>
<div class="text-center">
  <%= link_to 'Back', candidate_details_path,class:"btn btn-default" %>
</div>

Work Project 4/app/views/candidate_details/show.html.erb
<h1>Read Candidate</h1>
<div class="table-responsive table-bordered">
  <table class="table">
    <tbody>
    <tr>
      <td>
        <%=label_tag "S.No"%> :
        <%=@candidate_detail.id %>
      </td>
      <td>
        <%=label_tag "Source of Registration" %> :
        <%=@candidate_detail.src_reg %>
      </td>
      <td>
        <%=label_tag "Zone" %> :
        <%=@candidate_detail.zone%>
      </td>
      <td>
        <%=label_tag "Date of registration" %> :
        <%=@candidate_detail.DOR %>
      </td>
    </tr>
    <tr>
      <td>
        <%=label_tag "Registration number" %> :
        <%=@candidate_detail.reg_no %>
      </td>
      <td>
        <%=label_tag "Name" %> :
        <%=@candidate_detail.name%>
      </td>
      <td>
        <%=label_tag "Gender" %> :
        <%=@candidate_detail.gender %>
      </td>
      <td>
        <%=label_tag "Age" %> :
        <%=@candidate_detail.age %>
      </td>
    </tr>
    <tr>
      <td>
        <%=label_tag "Address" %> :
        <%=@candidate_detail.address %>
      </td>
      <td>
        <%=label_tag "branch" %> :
        <%=@candidate_detail.branch %>
      </td>
      <td>
        <%=label_tag "Email" %> :
        <%=@candidate_detail.email %>
      </td>
      <td>
        <%=label_tag "Contact number" %> :
        <%=@candidate_detail.contact_no %>
      </td>
    </tr>
    <tr>
      <td>
        <%=label_tag "State" %> :
        <%=@candidate_detail.state%>
      </td>
      <td>
        <%=label_tag "Qualification" %> :
        <%=@candidate_detail.qualification%>
      </td>
      <td>
        <%=label_tag "Specialization" %> :
        <%=@candidate_detail.specialization%>
      </td>
      <td>
        <%=label_tag "Experience" %> :
        <%=@candidate_detail.experience %>
      </td>
    </tr>
    <tr>
      <td>
        <%=label_tag "Remarks Mobility" %> :
        <%=@candidate_detail.remarks_mobility %>
      </td>
      <td>
        <%=label_tag "Date of closure" %> :
        <%=@candidate_detail.DOC %>
      </td>
      <td>
        <%=label_tag "Status" %> :
        <%=@candidate_detail.status %>
      </td>
      <td>
      </td>
    </tr>
    </tbody>
  </table>
</div>
<br>
<div class="text-center">
<%= link_to 'Edit', edit_candidate_detail_path(@candidate_detail),class:"btn btn-default" %> |
<%= link_to 'Back', candidate_details_path ,class:"btn btn-default"%>
</div>