Work Project 4/config/routes.rb
Rails.application.routes.draw do
  get 'Filter', to: "filter_page#filter_menu", as:"filter"
  post "Filter_Result",to: "filter_page#filter_result", as: "filter_result"

  root 'candidate_details#index'
  resources :candidate_details
  devise_for :users
  get "Admin_Panel", to: "admin_control#admin_panel", as:"panel"
  get "Admin_Panel_Create", to:"admin_control#admin_panel_create", as:"panel_create"
  post "Admin_Panel", to: "admin_page#admin_panel"
  get "Admin_Panel_Edit", to: "admin_control#admin_panel_update",as: "panel_edit"
  get "Admin_Panel_Delete", to: "admin_control#admin_panel_delete",as: "panel_delete"
  post "Create_User",to: "admin_control#create_user",as:"create_user"
  post "Edit_User", to:"admin_control#edit_user",as:"edit_user"
  post "Delete_User", to:"admin_control#delete_user",as:"delete_user"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Work Project 4/app/controllers/filter_page_controller.rb
class FilterPageController < ApplicationController
  def filter_menu
  end

  def filter_result
    param_list=[:s_no,:src_reg,:zone,:DOR,:reg_no,:name,:gender,:age,:address,:branch,:email,:contact_no,:state,:qualification,:specialization,:experience,:remarks_mobility,:DOC,:status]
    param_string=["s_no","src_reg","zone","DOR","reg_no","name","gender","age","address","branch","email","contact_no","state","qualification","specialization","experience","remarks_mobility","DOC","status"]
    param_query_list=[]
    param_query=""
    for i in (0..18)
      unless params[param_list[i]].blank?
        param_query_list.push(params[param_list[i]])
        param_query+=param_string[i]+"= ? and "
      end
    end
    complete_sql_query="SELECT * FROM candidate_details WHERE "+param_query[0..param_query.length-5]+" ;"
    print complete_sql_query
    if param_query==""

      redirect_to filter_path,notice: "Please fill at least one field."
    else
      @filter_result=CandidateDetail.filter_result(complete_sql_query,param_query_list)
      @filter_count=CandidateDetail.filter_count(complete_sql_query,param_query_list)

    end



  end
end

Work Project 4/app/views/filter_page/filter_menu.html.erb
<h1>Filter Menu</h1>
    <%= form_tag filter_result_path do |form| %>
      <div class="table-responsive table-bordered">
        <table class="table">
          <tbody>
          <tr>
            <td>
              <div class="field">
                <%= label_tag :s_no ,"S.No."%><br>
                <%= number_field_tag :s_no %>
              </div>
            </td>
            <td>
              <div class="field">
                <%= label_tag :src_reg,"Source of registration" %>
                <%= text_field_tag :src_reg %>
              </div>
            </td>
            <td>
              <div class="field">
                <%= label_tag :zone ,"Zone"%>
                <%= text_field_tag :zone %>
              </div>
            </td>
            <td>
              <div class="field">
                <%= label_tag :DOR ,"Date of registration"%><br>
                <%= date_field_tag :DOR %>
              </div>
            </td>
          </tr>
          <tr>
            <td>
              <div class="field">
                <%= label_tag :reg_no ,"Registration number"%>
                <%= text_field_tag :reg_no %>
              </div>
            </td>
            <td>
              <div class="field">
                <%= label_tag :name ,"Name"%>
                <%= text_field_tag :name %>
              </div>
            </td>
            <td>
              <div class="field">
                <%= label_tag :gender,"Gender" %>
                <%= text_field_tag :gender %>
              </div>
            </td>
            <td>
              <div class="field">
                <%= label_tag :age ,"Age"%><br>
                <%= number_field_tag :age %>
              </div>
            </td>
          </tr>
          <tr>
            <td>
              <div class="field">
                <%= label_tag :address ,"Address"%><br>
                <%= text_area_tag :address %>
              </div>
            </td>
            <td>
              <div class="field">
                <%= label_tag :branch,"Branch" %>
                <%= text_field_tag :branch %>
              </div>
            </td>
            <td>
              <div class="field">
                <%= label_tag :email,"Email" %>
                <%= text_field_tag :email %>
              </div>
            </td>
            <td>
              <div class="field">
                <%= label_tag :contact_no,"Contact number" %><br>
                <%= number_field_tag :contact_no %>
              </div>
            </td>
          </tr>
          <tr>
            <td>
              <div class="field">
                <%= label_tag :state,"State" %><br>
                <%= select_tag :state,options_for_select( ["Andhra Pradesh",
                                         "Arunachal Pradesh",
                                         "Assam",
                                         "Bihar",
                                         "Chhattisgarh",
                                         "Chandigarh",
                                         "Dadra and Nagar Haveli",
                                         "Daman and Diu",
                                         "Delhi",
                                         "Goa",
                                         "Gujarat",
                                         "Haryana",
                                         "Himachal Pradesh",
                                         "Jammu and Kashmir",
                                         "Jharkhand",
                                         "Karnataka",
                                         "Kerala",
                                         "Madhya Pradesh",
                                         "Maharashtra",
                                         "Manipur",
                                         "Meghalaya",
                                         "Mizoram",
                                         "Nagaland",
                                         "Orissa",
                                         "Punjab",
                                         "Pondicherry",
                                         "Rajasthan",
                                         "Sikkim",
                                         "Tamil Nadu",
                                         "Tripura",
                                         "Uttar Pradesh",
                                         "Uttarakhand",
                                         "West Bengal"]),:include_blank=>true%>
              </div>
            </td>
            <td>
              <div class="field">
                <%= label_tag :qualification,"Qualification" %>
                <%= text_field_tag :qualification %>
              </div>
            </td>
            <td>
              <div class="field">
                <%= label_tag :specialization ,"Specialization"%>
                <%= text_field_tag :specialization %>
              </div>
            </td>
            <td>
              <div class="field">
                <%= label_tag :experience,"Experience" %>
                <%= text_field_tag :experience %>
              </div>
            </td>
          </tr>
          <tr>
            <td>
              <div class="field">
                <%= label_tag :remarks_mobility ,"Remarks Mobility"%><br>
                <%= select_tag :remarks_mobility,options_for_select([1,2,3,4,5,6,7,8,9,10]),:include_blank=>true %>
              </div>
            </td>
            <td>
              <div class="field">
                <%= label_tag :DOC ,"Date of closure"%><br>
                <%= date_field_tag :DOC%>
              </div>
            </td>
            <td>
              <div class="field">
                <%= label_tag :status,"Status" %><br>
                <%= select_tag :status,options_for_select(["Pending","Joined","Joining","Studying","Not interested","Not responding"]),:include_blank=>true %>
              </div>
            </td>
            <td>

            </td>
          </tr>
          </tbody>
        </table>
      </div>
      <div class="actions">
        <%= submit_tag "Filter"%>
      </div>
    <% end %>

<div class="text-center">
  <%=link_to "Back",candidate_details_path,class: "btn btn-default" %>
</div>

Work Project 4/app/views/filter_page/filter_result.html.erb
<h1>Filter Result</h1>
<p class="alert alert-success"><%=@filter_count %> records found.</p>
<div class="table-responsive table-bordered">
  <table class="table">
    <thead>
    <tr>
      <th>S.No.</th>
      <th>Source of Registration</th>
      <th>Zone</th>
      <th>Date of Registration</th>
      <th>Registration Number</th>
      <th>Name</th>
      <th>Gender</th>
      <th>Age</th>
      <th>Address</th>
      <th>Branch</th>
      <th>Email</th>
      <th>Contact Number</th>
      <th>State</th>
      <th>Qualification</th>
      <th>Specialization</th>
      <th>Experience</th>
      <th>Remarks Mobility</th>
      <th>Date of Closure</th>
      <th>Status</th>
      <th colspan="2"></th>
    </tr>
    </thead>
    <tbody>
      <% @filter_result.each do |result| %>
      <tr>
        <td><%=result.s_no %> </td>
        <td><%=result.src_reg %> </td>
        <td><%=result.zone %> </td>
        <td><%=result.DOR %> </td>
        <td><%=result.reg_no %> </td>
        <td><%=result.name %> </td>
        <td><%=result.gender %> </td>
        <td><%=result.age %> </td>
        <td><%=result.address %> </td>
        <td><%=result.branch %> </td>
        <td><%=result.email %> </td>
        <td><%=result.contact_no %> </td>
        <td><%=result.state %> </td>
        <td><%=result.qualification %> </td>
        <td><%=result.specialization %> </td>
        <td><%=result.experience %> </td>
        <td><%=result.remarks_mobility %> </td>
        <td><%=result.DOC %> </td>
        <td><%=result.status %> </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>
<div class="text-center">
  <%=link_to "Back",filter_path,class: "btn btn-default" %>
</div>